components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          description: product title definition
        photo:
          type: string
          description: product photo url
        category:
          type: string
          description: product category definition
        description:
          type: string
          description: a simplified product description
        rating:
          type: number
          description: product rating on a five-star scale
        price:
          type: number
          description: product price expressed with decimal notation
        stock:
          type: number
          description: product available stock
      example:
        title: ROG Swift OLED PG32UCDM          
        photo: https://firebasestorage.googleapis.com/v0/b/coderserver-1ccaf.appspot.com/o/products%2Fmonitor%20ROG%20Swift%20OLED%20PG32UCDM.webp?alt=media&token=2354e4cc-cfb1-42b2-85dd-7b0de1e70b1d
        category: monitors
        description: ROG Swift OLED PG32UCDM gaming monitor ― 32-inch (31.5 inch viewable) 4K (3840 x 2160) QD-OLED panel, 240 Hz, 0.03 ms (GTG), G-SYNC compatible, custom heatsink, graphene film, uniform brightness, 99% DCI-P3, True 10-bit, 90 W Type-C, and ASUS DisplayWidget Center
        rating: 5
        price: 399.99
        stock: 6