apiVersion: v1
kind: Service
metadata:
  name: coderserver
spec:
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coderserver
spec:
  replicas: 10
  selector:
    matchLabels:
      app: coderserver
  template:
      metadata:
        labels:
          app: coderserver
      spec:
        containers:
        - name: app
          image: arielend/coderserver:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always